#!/bin/bash
#-----------------------------------------------------------
# Description: Lite Tweaks - Empty Trash Bin
# Authors: Misko_2083, Jerry Bezencon 2015
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

TRASHCACHESIZE=$(du -sh $HOME/.local/share/Trash/ | awk '{print $1}' | sed 's/$/B/')

# Main window dialogue.
 INSTALLER_TITLE="Empty Trash Bin
-----------------------------------------------------------------------------------------------------------------------------------
This will process will empty your Trash bin.

The current total size of your Trash bin is <b>$TRASHCACHESIZE</b>

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/pixmaps/litecleaner.png"
 APPNAME="Empty Trash Bin"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        rm -rf $HOME/.local/share/Trash/files/* | zenity --progress --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst your Trash bin is emptied..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="$APPNAME Clean Complete."
	exit;
else
	exit
fi

exit 0
