#!/bin/bash
#-----------------------------------------------------------
# Description: Lite Tweaks - Delete Thumbnail Cache
# Authors: Misko_2083, Jerry Bezencon 2015
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

if [ $(du -sk $HOME/.thumbnails/ | awk '{print $1}')  -gt 100  ]; then
THUMBCACHESIZE=$(du -sh $HOME/.thumbnails/ | awk '{print $1}' | sed 's/$/B/')
else
THUMBCACHESIZE=$(echo "0kB")
fi

# Main window dialogue.
 INSTALLER_TITLE="Delete Thumbnail Cache
------------------------------------------------------------------------------------------------------------
This will empty your thumbnail cache.

You currently have <b>$THUMBCACHESIZE</b> of space that can be cleaned.

When you click on Yes, this window will close and the process will begin.

------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/pixmaps/litecleaner.png"
 APPNAME="Delete Thumbnail Cache"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        rm -rf $HOME/.thumbnails/* | zenity --progress --title="Deleting Thumbnail Cache" --window-icon="${INSTALL_ICON}" --text="Please wait whilst your thumbnail cache is deleted..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME Cleaner" --window-icon="${INSTALL_ICON}" --text="$APPNAME Complete."
	exit;
else
	exit
fi

exit 0
