#!/bin/bash
#-----------------------------------------------------------
# Description: Linux Lite Cleaner Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

CACHESIZE=$(du -sh /var/cache/apt/archives/ | awk '{print $1}')

# Main window dialogue.
 INSTALLER_TITLE="Package Cache Cleaner
---------------------------------------------------------------------------------------------------------------------
This will clean your package cache.

You currently have <b>$CACHESIZE</b> of space that can be cleaned.
When you click on Yes, this window will close and the process will begin.

---------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Package Cache"
        
        zenity --question --title="$APPNAME Cleaner" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        gksudo -g --message 'To run this cleaner your password is required. Enter your password, or press Cancel.' "sudo apt-get clean" | zenity --progress --title="Cleaning $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst your $APPNAME is cleaned..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME Cleaner" --window-icon=/usr/share/icons/zenity-llcc.png --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME Cleaner" --window-icon="${INSTALL_ICON}" --text="$APPNAME Clean Complete."
	exit;
else
	exit
fi

exit 0
