#!/bin/bash
#-----------------------------------------------------------
# Description: Linux Lite Cleaner Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

# Main window dialogue.
 INSTALLER_TITLE="Remove Unneeded Packages
-----------------------------------------------------------------------------------------------------------------------------------
This will remove packages automatically installed for programs that are no longer present.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Remove Unneeded Packages"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        gksudo -g --message 'To run this cleaner your password is required. Enter your password, or press Cancel.' "sudo apt-get autoremove" | zenity --progress --title="Cleaning $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst unneeded packages are removed..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME Cleaner" --window-icon="${INSTALL_ICON}" --text="$APPNAME Clean Complete."
	exit;
else
	exit
fi

exit 0
