#!/bin/bash
#-----------------------------------------------------------
# Description: Linux Lite Cleaner Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

TRASHCACHESIZE=$(du -sh /home/*/.local/share/Trash/ | awk '{print $1}')

# Main window dialogue.
 INSTALLER_TITLE="Empty all Trash Bins
-----------------------------------------------------------------------------------------------------------------------------------
This will process will empty the Trash bins of <b>all</b> users with an account
on this computer. Before proceeding, ensure that this something other users
have consented to first.

The current total size of all Trash bins is <b>$TRASHCACHESIZE</b>

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Empty all Trash Bins"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        gksudo -g --message 'To run this cleaner your password is required. Enter your password, or press Cancel.' "stdbuf -oL /bin/bash \-c '(sudo rm -rf /home/*/.local/share/Trash/files/*)" | zenity --progress --title="Cleaning $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst all Trash bins are emptied..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="$APPNAME Clean Complete."
	exit;
else
	exit
fi

exit 0
