#!/bin/bash
#-----------------------------------------------------------
# Description: Linux Lite Cleaner Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

# Main window dialogue.
 INSTALLER_TITLE="Remove Unneeded Packages
-----------------------------------------------------------------------------------------------------------------------------------
This will remove packages automatically installed for programs that are no longer present.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/pixmaps/litecleaner.png"
 APPNAME="Remove Unneeded Packages"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
x=$( gksudo -g --message 'To update package lists your password is required. Enter your password, or press Cancel.' "stdbuf -oL /bin/bash \-c '(sudo sh /usr/scripts/clean/kernels ) 2>&1 | tee /var/log/kernelremoval.log'" |
stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p'|
zenity --progress --title="Updating" --pulsate \
--width=600 --auto-close )


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --question --title="$APPNAME Updates" --window-icon=/usr/share/icons/zenity-llcc.png --text="Updates have finished installing.\n\nWould you like to view the $APPNAME Updates log?"; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME Updates" --window-icon="${INSTALL_ICON}" --text="$APPNAME Updates Complete."
	exit;
else
	leafpad /var/log/kernelremoval.log
fi

exit 0
