#!/bin/bash
#-----------------------------------------------------------
# Description: Linux Lite Cleaner Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-----------------------------------------------------------

THUMBCACHESIZE=$(du -sh /home/*/.thumbnails/ | awk '{print $1}')

# Main window dialogue.
 INSTALLER_TITLE="Delete Thumbnail Caches
------------------------------------------------------------------------------------------------------------
This will delete thumbnail caches from <b>all</b> users home folders.

You currently have <b>$THUMBCACHESIZE</b> of space that can be cleaned.

When you click on Yes, this window will close and the process will begin.

------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the cleaning process.\nWould you like to continue?"

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Delete Thumbnail Caches"
        
        zenity --question --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        gksudo -g --message 'To run this cleaner your password is required. Enter your password, or press Cancel.' "stdbuf -oL /bin/bash \-c '(sudo rm -rf /home/*/.thumbnails/*)" | zenity --progress --title="Deleting Thumbnail Caches" --window-icon="${INSTALL_ICON}" --text="Please wait whilst thumbnail caches are deleted..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME has failed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="$APPNAME Cleaner" --window-icon="${INSTALL_ICON}" --text="$APPNAME Complete."
	exit;
else
	exit
fi

exit 0
